# Generated by Django 4.1.3 on 2022-11-16 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='availible',
            new_name='available',
        ),
        migrations.AddField(
            model_name='product',
            name='Price',
            field=models.DecimalField(decimal_places=2, default='2.5', max_digits=10),
            preserve_default=False,
        ),
    ]
